export const NEWS_REQUEST = 'NEWS_REQUEST';
export const NEWS_FAILURE = 'NEWS_FAILURE';
export const NEWS_SUCCESS = 'NEWS_SUCCESS';
export const LAST_NEWS_REQUEST = 'LAST_NEWS_REQUEST';
export const LAST_NEWS_FAILURE = 'LAST_NEWS_FAILURE';
export const LAST_NEWS_SUCCESS = 'LAST_NEWS_SUCCESS';
